#!/usr/bin/env python

Import('env')

if env['unity']:
    env.add_source_files(env.servers_sources, "#misc/scu/SCU_servers_physics_2d.cc")
else:
    env.add_source_files(env.servers_sources, "*.cpp")
