// Single compilation unit
#include "area_2d_sw.cpp"
#include "area_pair_2d_sw.cpp"
#include "body_2d_sw.cpp"
#include "body_pair_2d_sw.cpp"
#include "broad_phase_2d_basic.cpp"
#include "broad_phase_2d_hash_grid.cpp"
#include "broad_phase_2d_sw.cpp"
#include "collision_object_2d_sw.cpp"
#include "collision_solver_2d_sat.cpp"
#include "collision_solver_2d_sw.cpp"
#include "joints_2d_sw.cpp"
#include "physics_2d_server_sw.cpp"
#include "physics_2d_server_wrap_mt.cpp"
#include "shape_2d_sw.cpp"
#include "space_2d_sw.cpp"
#include "step_2d_sw.cpp"
