#!/usr/bin/env python

Import('env')
Import('env_modules')

env_bullet = env_modules.Clone()

# Thirdparty source files

if env['builtin_bullet']:
    # Build only version 2 for now (as of 2.87)
    thirdparty_dir = "#thirdparty/bullet/"

    bullet2_src = [
        # BulletCollision
          "btBulletCollisionAll.cpp"

       
        # BulletSoftBody
        , "BulletSoftBody/btSoftBody.cpp"
        , "BulletSoftBody/btSoftBodyConcaveCollisionAlgorithm.cpp"
        , "BulletSoftBody/btSoftBodyHelpers.cpp"
        , "BulletSoftBody/btSoftBodyRigidBodyCollisionConfiguration.cpp"
        , "BulletSoftBody/btSoftRigidCollisionAlgorithm.cpp"
        , "BulletSoftBody/btSoftRigidDynamicsWorld.cpp"
        , "BulletSoftBody/btSoftMultiBodyDynamicsWorld.cpp"
        , "BulletSoftBody/btSoftSoftCollisionAlgorithm.cpp"
        , "BulletSoftBody/btDefaultSoftBodySolver.cpp"
        
        
        , "btBulletDynamicsAll.cpp"
        , "btLinearMathAll.cpp"
    ]

    thirdparty_sources = [thirdparty_dir + file for file in bullet2_src]

    # Treat Bullet headers as system headers to avoid raising warnings. Not supported on MSVC.
    if not env.msvc:
        env_bullet.Append(CPPFLAGS=['-isystem', Dir(thirdparty_dir).path])
    else:
        env_bullet.Prepend(CPPPATH=[thirdparty_dir])
    # if env['target'] == "debug" or env['target'] == "release_debug":
    #     env_bullet.Append(CPPDEFINES=['BT_DEBUG'])

    env_thirdparty = env_bullet.Clone()
    env_thirdparty.disable_warnings()
    env_thirdparty.add_source_files(env.modules_sources, thirdparty_sources)


# Godot source files
env_bullet.add_source_files(env.modules_sources, "SCU.cpp")
