#!/usr/bin/env python

Import('env')

#env.add_source_files(env.editor_sources, "*.cpp")
env.add_source_files(env.editor_sources, "SCU.cpp")
env.add_source_files(env.editor_sources, "script_text_editor.cpp")
