// Single Compilation Unit
#define SCU_IDENT(x) x
#define SCU_XSTR(x) #x
#define SCU_STR(x) SCU_XSTR(x)
#define SCU_PATH(x,y) SCU_STR(SCU_IDENT(x)SCU_IDENT(y))
#define SCU_DIR thirdparty/assimp/code/

#include SCU_PATH(SCU_DIR,CApi/AssimpCExport.cpp)
#include SCU_PATH(SCU_DIR,CApi/CInterfaceIOWrapper.cpp)
#include SCU_PATH(SCU_DIR,Common/Assimp.cpp)
#include SCU_PATH(SCU_DIR,Common/BaseImporter.cpp)
#include SCU_PATH(SCU_DIR,Common/BaseProcess.cpp)
#include SCU_PATH(SCU_DIR,Common/Bitmap.cpp)
#include SCU_PATH(SCU_DIR,Common/CreateAnimMesh.cpp)
#include SCU_PATH(SCU_DIR,Common/DefaultIOStream.cpp)
#include SCU_PATH(SCU_DIR,Common/DefaultIOSystem.cpp)
#include SCU_PATH(SCU_DIR,Common/DefaultLogger.cpp)
#include SCU_PATH(SCU_DIR,Common/Exporter.cpp)
#include SCU_PATH(SCU_DIR,Common/Importer.cpp)
#include SCU_PATH(SCU_DIR,Common/ImporterRegistry.cpp)
#include SCU_PATH(SCU_DIR,Common/PostStepRegistry.cpp)
#include SCU_PATH(SCU_DIR,Common/RemoveComments.cpp)
#include SCU_PATH(SCU_DIR,Common/SGSpatialSort.cpp)
#include SCU_PATH(SCU_DIR,Common/SceneCombiner.cpp)
#include SCU_PATH(SCU_DIR,Common/ScenePreprocessor.cpp)
#include SCU_PATH(SCU_DIR,Common/SkeletonMeshBuilder.cpp)
#include SCU_PATH(SCU_DIR,Common/SpatialSort.cpp)
#include SCU_PATH(SCU_DIR,Common/SplitByBoneCountProcess.cpp)
#include SCU_PATH(SCU_DIR,Common/StandardShapes.cpp)
#include SCU_PATH(SCU_DIR,Common/Subdivision.cpp)
#include SCU_PATH(SCU_DIR,Common/TargetAnimation.cpp)
#include SCU_PATH(SCU_DIR,Common/Version.cpp)
#include SCU_PATH(SCU_DIR,Common/VertexTriangleAdjacency.cpp)
#include SCU_PATH(SCU_DIR,Common/scene.cpp)
#include SCU_PATH(SCU_DIR,Common/simd.cpp)
#include SCU_PATH(SCU_DIR,MMD/MMDImporter.cpp)
#include SCU_PATH(SCU_DIR,MMD/MMDPmxParser.cpp)
#include SCU_PATH(SCU_DIR,Material/MaterialSystem.cpp)
#include SCU_PATH(SCU_DIR,PostProcessing/CalcTangentsProcess.cpp)
#include SCU_PATH(SCU_DIR,PostProcessing/ComputeUVMappingProcess.cpp)
#include SCU_PATH(SCU_DIR,PostProcessing/ConvertToLHProcess.cpp)
#include SCU_PATH(SCU_DIR,PostProcessing/DeboneProcess.cpp)
#include SCU_PATH(SCU_DIR,PostProcessing/DropFaceNormalsProcess.cpp)
#include SCU_PATH(SCU_DIR,PostProcessing/EmbedTexturesProcess.cpp)
#include SCU_PATH(SCU_DIR,PostProcessing/FindDegenerates.cpp)
#include SCU_PATH(SCU_DIR,PostProcessing/FindInstancesProcess.cpp)
#include SCU_PATH(SCU_DIR,PostProcessing/FindInvalidDataProcess.cpp)
#include SCU_PATH(SCU_DIR,PostProcessing/FixNormalsStep.cpp)
#include SCU_PATH(SCU_DIR,PostProcessing/GenBoundingBoxesProcess.cpp)
#include SCU_PATH(SCU_DIR,PostProcessing/GenFaceNormalsProcess.cpp)
#include SCU_PATH(SCU_DIR,PostProcessing/GenVertexNormalsProcess.cpp)
#include SCU_PATH(SCU_DIR,PostProcessing/ImproveCacheLocality.cpp)
#include SCU_PATH(SCU_DIR,PostProcessing/JoinVerticesProcess.cpp)
#include SCU_PATH(SCU_DIR,PostProcessing/LimitBoneWeightsProcess.cpp)
#include SCU_PATH(SCU_DIR,PostProcessing/MakeVerboseFormat.cpp)
#include SCU_PATH(SCU_DIR,PostProcessing/OptimizeGraph.cpp)
#include SCU_PATH(SCU_DIR,PostProcessing/OptimizeMeshes.cpp)
#include SCU_PATH(SCU_DIR,PostProcessing/PretransformVertices.cpp)
#include SCU_PATH(SCU_DIR,PostProcessing/ProcessHelper.cpp)
#include SCU_PATH(SCU_DIR,PostProcessing/RemoveRedundantMaterials.cpp)
#include SCU_PATH(SCU_DIR,PostProcessing/RemoveVCProcess.cpp)
#include SCU_PATH(SCU_DIR,PostProcessing/ScaleProcess.cpp)
#include SCU_PATH(SCU_DIR,PostProcessing/SortByPTypeProcess.cpp)
#include SCU_PATH(SCU_DIR,PostProcessing/SplitLargeMeshes.cpp)
#include SCU_PATH(SCU_DIR,PostProcessing/TextureTransform.cpp)
#include SCU_PATH(SCU_DIR,PostProcessing/TriangulateProcess.cpp)
#include SCU_PATH(SCU_DIR,PostProcessing/ValidateDataStructure.cpp)
