// Single Compilation Unit
#define SCU_IDENT(x) x
#define SCU_XSTR(x) #x
#define SCU_STR(x) SCU_XSTR(x)
#define SCU_PATH(x,y) SCU_STR(SCU_IDENT(x)SCU_IDENT(y))
#define SCU_DIR modules/gdnative/

#include SCU_PATH(SCU_DIR,gdnative.cpp)
#include SCU_PATH(SCU_DIR,gdnative_library_editor_plugin.cpp)
#include SCU_PATH(SCU_DIR,gdnative_library_singleton_editor.cpp)
#include SCU_PATH(SCU_DIR,register_types.cpp)
#include SCU_PATH(SCU_DIR,android/android_gdn.cpp)
#include SCU_PATH(SCU_DIR,gdnative/aabb.cpp)
#include SCU_PATH(SCU_DIR,gdnative/array.cpp)
#include SCU_PATH(SCU_DIR,gdnative/basis.cpp)
#include SCU_PATH(SCU_DIR,gdnative/color.cpp)
#include SCU_PATH(SCU_DIR,gdnative/dictionary.cpp)
#include SCU_PATH(SCU_DIR,gdnative/gdnative.cpp)
#include SCU_PATH(SCU_DIR,gdnative/node_path.cpp)
#include SCU_PATH(SCU_DIR,gdnative/plane.cpp)
#include SCU_PATH(SCU_DIR,gdnative/pool_arrays.cpp)
#include SCU_PATH(SCU_DIR,gdnative/quat.cpp)
#include SCU_PATH(SCU_DIR,gdnative/rect2.cpp)
#include SCU_PATH(SCU_DIR,gdnative/rid.cpp)
#include SCU_PATH(SCU_DIR,gdnative/string.cpp)
#include SCU_PATH(SCU_DIR,gdnative/string_name.cpp)
#include SCU_PATH(SCU_DIR,gdnative/transform.cpp)
#include SCU_PATH(SCU_DIR,gdnative/transform2d.cpp)
#include SCU_PATH(SCU_DIR,gdnative/variant.cpp)
#include SCU_PATH(SCU_DIR,gdnative/vector2.cpp)
#include SCU_PATH(SCU_DIR,gdnative/vector3.cpp)
#include SCU_PATH(SCU_DIR,nativescript/api_generator.cpp)
#include SCU_PATH(SCU_DIR,nativescript/godot_nativescript.cpp)
#include SCU_PATH(SCU_DIR,nativescript/nativescript.cpp)
#include SCU_PATH(SCU_DIR,nativescript/register_types.cpp)
