// Single Compilation Unit
#define SCU_IDENT(x) x
#define SCU_XSTR(x) #x
#define SCU_STR(x) SCU_XSTR(x)
#define SCU_PATH(x,y) SCU_STR(SCU_IDENT(x)SCU_IDENT(y))
#define SCU_DIR core/io/

#include SCU_PATH(SCU_DIR,compression.cpp)
#include SCU_PATH(SCU_DIR,config_file.cpp)
#include SCU_PATH(SCU_DIR,file_access_buffered.cpp)
#include SCU_PATH(SCU_DIR,file_access_compressed.cpp)
#include SCU_PATH(SCU_DIR,file_access_encrypted.cpp)
#include SCU_PATH(SCU_DIR,file_access_memory.cpp)
#include SCU_PATH(SCU_DIR,file_access_network.cpp)
#include SCU_PATH(SCU_DIR,file_access_pack.cpp)
#include SCU_PATH(SCU_DIR,file_access_zip.cpp)
#include SCU_PATH(SCU_DIR,http_client.cpp)
#include SCU_PATH(SCU_DIR,image_loader.cpp)
#include SCU_PATH(SCU_DIR,ip.cpp)
#include SCU_PATH(SCU_DIR,ip_address.cpp)
#include SCU_PATH(SCU_DIR,json.cpp)
#include SCU_PATH(SCU_DIR,logger.cpp)
#include SCU_PATH(SCU_DIR,marshalls.cpp)
#include SCU_PATH(SCU_DIR,multiplayer_api.cpp)
#include SCU_PATH(SCU_DIR,net_socket.cpp)
#include SCU_PATH(SCU_DIR,networked_multiplayer_peer.cpp)
#include SCU_PATH(SCU_DIR,packet_peer.cpp)
#include SCU_PATH(SCU_DIR,packet_peer_udp.cpp)
#include SCU_PATH(SCU_DIR,pck_packer.cpp)
#include SCU_PATH(SCU_DIR,resource_format_binary.cpp)
#include SCU_PATH(SCU_DIR,resource_importer.cpp)
#include SCU_PATH(SCU_DIR,resource_loader.cpp)
#include SCU_PATH(SCU_DIR,resource_saver.cpp)
#include SCU_PATH(SCU_DIR,stream_peer.cpp)
#include SCU_PATH(SCU_DIR,stream_peer_ssl.cpp)
#include SCU_PATH(SCU_DIR,stream_peer_tcp.cpp)
#include SCU_PATH(SCU_DIR,tcp_server.cpp)
#include SCU_PATH(SCU_DIR,translation_loader_po.cpp)
#include SCU_PATH(SCU_DIR,xml_parser.cpp)
#include SCU_PATH(SCU_DIR,zip_io.cpp)
