// Single Compilation Unit
#define SCU_IDENT(x) x
#define SCU_XSTR(x) #x
#define SCU_STR(x) SCU_XSTR(x)
#define SCU_PATH(x,y) SCU_STR(SCU_IDENT(x)SCU_IDENT(y))
#define SCU_DIR scene/2d/

#include SCU_PATH(SCU_DIR,animated_sprite.cpp)
#include SCU_PATH(SCU_DIR,area_2d.cpp)
#include SCU_PATH(SCU_DIR,audio_stream_player_2d.cpp)
#include SCU_PATH(SCU_DIR,back_buffer_copy.cpp)
#include SCU_PATH(SCU_DIR,camera_2d.cpp)
#include SCU_PATH(SCU_DIR,canvas_item.cpp)
#include SCU_PATH(SCU_DIR,canvas_modulate.cpp)
#include SCU_PATH(SCU_DIR,collision_object_2d.cpp)
#include SCU_PATH(SCU_DIR,collision_polygon_2d.cpp)
#include SCU_PATH(SCU_DIR,collision_shape_2d.cpp)
#include SCU_PATH(SCU_DIR,cpu_particles_2d.cpp)
#include SCU_PATH(SCU_DIR,joints_2d.cpp)
#include SCU_PATH(SCU_DIR,light_2d.cpp)
#include SCU_PATH(SCU_DIR,light_occluder_2d.cpp)
#include SCU_PATH(SCU_DIR,line_2d.cpp)
#include SCU_PATH(SCU_DIR,line_builder.cpp)
#include SCU_PATH(SCU_DIR,mesh_instance_2d.cpp)
#include SCU_PATH(SCU_DIR,multimesh_instance_2d.cpp)
#include SCU_PATH(SCU_DIR,navigation_2d.cpp)
#include SCU_PATH(SCU_DIR,navigation_polygon.cpp)
#include SCU_PATH(SCU_DIR,node_2d.cpp)
#include SCU_PATH(SCU_DIR,parallax_background.cpp)
#include SCU_PATH(SCU_DIR,parallax_layer.cpp)
#include SCU_PATH(SCU_DIR,particles_2d.cpp)
#include SCU_PATH(SCU_DIR,path_2d.cpp)
#include SCU_PATH(SCU_DIR,path_texture.cpp)
#include SCU_PATH(SCU_DIR,physics_body_2d.cpp)
#include SCU_PATH(SCU_DIR,polygon_2d.cpp)
#include SCU_PATH(SCU_DIR,position_2d.cpp)
#include SCU_PATH(SCU_DIR,ray_cast_2d.cpp)
#include SCU_PATH(SCU_DIR,remote_transform_2d.cpp)
#include SCU_PATH(SCU_DIR,skeleton_2d.cpp)
#include SCU_PATH(SCU_DIR,sprite.cpp)
#include SCU_PATH(SCU_DIR,tile_map.cpp)
#include SCU_PATH(SCU_DIR,touch_screen_button.cpp)
#include SCU_PATH(SCU_DIR,visibility_notifier_2d.cpp)
#include SCU_PATH(SCU_DIR,y_sort.cpp)
