// Single Compilation Unit
#define SCU_IDENT(x) x
#define SCU_XSTR(x) #x
#define SCU_STR(x) SCU_XSTR(x)
#define SCU_PATH(x,y) SCU_STR(SCU_IDENT(x)SCU_IDENT(y))
#define SCU_DIR core/

#include SCU_PATH(SCU_DIR,array.cpp)
#include SCU_PATH(SCU_DIR,class_db.cpp)
#include SCU_PATH(SCU_DIR,color.cpp)
#include SCU_PATH(SCU_DIR,command_queue_mt.cpp)
#include SCU_PATH(SCU_DIR,compressed_translation.cpp)
#include SCU_PATH(SCU_DIR,core_string_names.cpp)
#include SCU_PATH(SCU_DIR,dictionary.cpp)
#include SCU_PATH(SCU_DIR,engine.cpp)
#include SCU_PATH(SCU_DIR,error_macros.cpp)
#include SCU_PATH(SCU_DIR,func_ref.cpp)
#include SCU_PATH(SCU_DIR,global_constants.cpp)
#include SCU_PATH(SCU_DIR,image.cpp)
#include SCU_PATH(SCU_DIR,input_map.cpp)
#include SCU_PATH(SCU_DIR,message_queue.cpp)
#include SCU_PATH(SCU_DIR,method_bind.cpp)
#include SCU_PATH(SCU_DIR,node_path.cpp)
#include SCU_PATH(SCU_DIR,object.cpp)
#include SCU_PATH(SCU_DIR,packed_data_container.cpp)
#include SCU_PATH(SCU_DIR,path_remap.cpp)
#include SCU_PATH(SCU_DIR,pool_allocator.cpp)
#include SCU_PATH(SCU_DIR,pool_vector.cpp)
#include SCU_PATH(SCU_DIR,print_string.cpp)
#include SCU_PATH(SCU_DIR,project_settings.cpp)
#include SCU_PATH(SCU_DIR,ref_ptr.cpp)
#include SCU_PATH(SCU_DIR,reference.cpp)
#include SCU_PATH(SCU_DIR,register_core_types.cpp)
#include SCU_PATH(SCU_DIR,resource.cpp)
#include SCU_PATH(SCU_DIR,rid.cpp)
#include SCU_PATH(SCU_DIR,safe_refcount.cpp)
#include SCU_PATH(SCU_DIR,script_debugger_local.cpp)
#include SCU_PATH(SCU_DIR,script_debugger_remote.cpp)
#include SCU_PATH(SCU_DIR,script_encryption_key.gen.cpp)
#include SCU_PATH(SCU_DIR,script_language.cpp)
#include SCU_PATH(SCU_DIR,string_builder.cpp)
#include SCU_PATH(SCU_DIR,string_name.cpp)
#include SCU_PATH(SCU_DIR,translation.cpp)
#include SCU_PATH(SCU_DIR,undo_redo.cpp)
#include SCU_PATH(SCU_DIR,ustring.cpp)
#include SCU_PATH(SCU_DIR,variant.cpp)
#include SCU_PATH(SCU_DIR,variant_op.cpp)
#include SCU_PATH(SCU_DIR,variant_parser.cpp)
