// Single Compilation Unit
#define SCU_IDENT(x) x
#define SCU_XSTR(x) #x
#define SCU_STR(x) SCU_XSTR(x)
#define SCU_PATH(x,y) SCU_STR(SCU_IDENT(x)SCU_IDENT(y))
#define SCU_DIR editor/plugins/

#include SCU_PATH(SCU_DIR,abstract_polygon_2d_editor.cpp)
#include SCU_PATH(SCU_DIR,animation_blend_space_1d_editor.cpp)
#include SCU_PATH(SCU_DIR,animation_blend_space_2d_editor.cpp)
#include SCU_PATH(SCU_DIR,animation_blend_tree_editor_plugin.cpp)
#include SCU_PATH(SCU_DIR,animation_player_editor_plugin.cpp)
#include SCU_PATH(SCU_DIR,animation_state_machine_editor.cpp)
#include SCU_PATH(SCU_DIR,animation_tree_editor_plugin.cpp)
#include SCU_PATH(SCU_DIR,animation_tree_player_editor_plugin.cpp)
#include SCU_PATH(SCU_DIR,asset_library_editor_plugin.cpp)
#include SCU_PATH(SCU_DIR,audio_stream_editor_plugin.cpp)
#include SCU_PATH(SCU_DIR,baked_lightmap_editor_plugin.cpp)
#include SCU_PATH(SCU_DIR,camera_editor_plugin.cpp)
#include SCU_PATH(SCU_DIR,canvas_item_editor_plugin.cpp)
#include SCU_PATH(SCU_DIR,collision_polygon_2d_editor_plugin.cpp)
#include SCU_PATH(SCU_DIR,collision_polygon_editor_plugin.cpp)
#include SCU_PATH(SCU_DIR,collision_shape_2d_editor_plugin.cpp)
#include SCU_PATH(SCU_DIR,cpu_particles_2d_editor_plugin.cpp)
#include SCU_PATH(SCU_DIR,cpu_particles_editor_plugin.cpp)
#include SCU_PATH(SCU_DIR,curve_editor_plugin.cpp)
#include SCU_PATH(SCU_DIR,editor_preview_plugins.cpp)
#include SCU_PATH(SCU_DIR,gi_probe_editor_plugin.cpp)
#include SCU_PATH(SCU_DIR,gradient_editor_plugin.cpp)
#include SCU_PATH(SCU_DIR,item_list_editor_plugin.cpp)
#include SCU_PATH(SCU_DIR,light_occluder_2d_editor_plugin.cpp)
#include SCU_PATH(SCU_DIR,line_2d_editor_plugin.cpp)
#include SCU_PATH(SCU_DIR,material_editor_plugin.cpp)
#include SCU_PATH(SCU_DIR,mesh_editor_plugin.cpp)
#include SCU_PATH(SCU_DIR,mesh_instance_editor_plugin.cpp)
#include SCU_PATH(SCU_DIR,mesh_library_editor_plugin.cpp)
#include SCU_PATH(SCU_DIR,multimesh_editor_plugin.cpp)
#include SCU_PATH(SCU_DIR,navigation_polygon_editor_plugin.cpp)
#include SCU_PATH(SCU_DIR,particles_2d_editor_plugin.cpp)
#include SCU_PATH(SCU_DIR,particles_editor_plugin.cpp)
#include SCU_PATH(SCU_DIR,path_2d_editor_plugin.cpp)
#include SCU_PATH(SCU_DIR,path_editor_plugin.cpp)
#include SCU_PATH(SCU_DIR,physical_bone_plugin.cpp)
#include SCU_PATH(SCU_DIR,polygon_2d_editor_plugin.cpp)
#include SCU_PATH(SCU_DIR,resource_preloader_editor_plugin.cpp)
#include SCU_PATH(SCU_DIR,root_motion_editor_plugin.cpp)
#include SCU_PATH(SCU_DIR,script_editor_plugin.cpp)
#include SCU_PATH(SCU_DIR,shader_editor_plugin.cpp)
#include SCU_PATH(SCU_DIR,skeleton_2d_editor_plugin.cpp)
#include SCU_PATH(SCU_DIR,skeleton_editor_plugin.cpp)
#include SCU_PATH(SCU_DIR,skeleton_ik_editor_plugin.cpp)
#include SCU_PATH(SCU_DIR,spatial_editor_plugin.cpp)
#include SCU_PATH(SCU_DIR,sprite_editor_plugin.cpp)
#include SCU_PATH(SCU_DIR,sprite_frames_editor_plugin.cpp)
#include SCU_PATH(SCU_DIR,style_box_editor_plugin.cpp)
#include SCU_PATH(SCU_DIR,text_editor.cpp)
#include SCU_PATH(SCU_DIR,texture_editor_plugin.cpp)
#include SCU_PATH(SCU_DIR,texture_region_editor_plugin.cpp)
#include SCU_PATH(SCU_DIR,theme_editor_plugin.cpp)
#include SCU_PATH(SCU_DIR,tile_map_editor_plugin.cpp)
#include SCU_PATH(SCU_DIR,tile_set_editor_plugin.cpp)
#include SCU_PATH(SCU_DIR,visual_shader_editor_plugin.cpp)
