// Single Compilation Unit
#define SCU_IDENT(x) x
#define SCU_XSTR(x) #x
#define SCU_STR(x) SCU_XSTR(x)
#define SCU_PATH(x,y) SCU_STR(SCU_IDENT(x)SCU_IDENT(y))
#define SCU_DIR scene/3d/

#include SCU_PATH(SCU_DIR,area.cpp)
#include SCU_PATH(SCU_DIR,arvr_nodes.cpp)
#include SCU_PATH(SCU_DIR,audio_stream_player_3d.cpp)
#include SCU_PATH(SCU_DIR,baked_lightmap.cpp)
#include SCU_PATH(SCU_DIR,bone_attachment.cpp)
#include SCU_PATH(SCU_DIR,camera.cpp)
#include SCU_PATH(SCU_DIR,collision_object.cpp)
#include SCU_PATH(SCU_DIR,collision_polygon.cpp)
#include SCU_PATH(SCU_DIR,collision_shape.cpp)
#include SCU_PATH(SCU_DIR,cpu_particles.cpp)
#include SCU_PATH(SCU_DIR,gi_probe.cpp)
#include SCU_PATH(SCU_DIR,immediate_geometry.cpp)
#include SCU_PATH(SCU_DIR,interpolated_camera.cpp)
#include SCU_PATH(SCU_DIR,light.cpp)
#include SCU_PATH(SCU_DIR,listener.cpp)
#include SCU_PATH(SCU_DIR,mesh_instance.cpp)
#include SCU_PATH(SCU_DIR,multimesh_instance.cpp)
#include SCU_PATH(SCU_DIR,navigation.cpp)
#include SCU_PATH(SCU_DIR,navigation_mesh.cpp)
#include SCU_PATH(SCU_DIR,particles.cpp)
#include SCU_PATH(SCU_DIR,path.cpp)
#include SCU_PATH(SCU_DIR,physics_body.cpp)
#include SCU_PATH(SCU_DIR,physics_joint.cpp)
#include SCU_PATH(SCU_DIR,portal.cpp)
#include SCU_PATH(SCU_DIR,position_3d.cpp)
#include SCU_PATH(SCU_DIR,proximity_group.cpp)
#include SCU_PATH(SCU_DIR,ray_cast.cpp)
#include SCU_PATH(SCU_DIR,reflection_probe.cpp)
#include SCU_PATH(SCU_DIR,remote_transform.cpp)
#include SCU_PATH(SCU_DIR,room_instance.cpp)
#include SCU_PATH(SCU_DIR,skeleton.cpp)
#include SCU_PATH(SCU_DIR,soft_body.cpp)
#include SCU_PATH(SCU_DIR,spatial.cpp)
#include SCU_PATH(SCU_DIR,spatial_velocity_tracker.cpp)
#include SCU_PATH(SCU_DIR,spring_arm.cpp)
#include SCU_PATH(SCU_DIR,sprite_3d.cpp)
#include SCU_PATH(SCU_DIR,vehicle_body.cpp)
#include SCU_PATH(SCU_DIR,visibility_notifier.cpp)
#include SCU_PATH(SCU_DIR,visual_instance.cpp)
#include SCU_PATH(SCU_DIR,voxel_light_baker.cpp)
#include SCU_PATH(SCU_DIR,world_environment.cpp)
