#!/usr/bin/env python

Import('env')

env.servers_sources = []
if env['unity']:
    env.add_source_files(env.servers_sources, "#misc/scu/SCU_servers.cc")
else:
    env.add_source_files(env.servers_sources, "*.cpp")


SConscript('arvr/SCsub')
SConscript('camera/SCsub')
SConscript('physics/SCsub')
SConscript('physics_2d/SCsub')
SConscript('visual/SCsub')
SConscript('audio/SCsub')

lib = env.add_library("servers", env.servers_sources)

env.Prepend(LIBS=[lib])
