#!/usr/bin/env python

Import("env")

env.servers_sources = []

if not env.add_source_files_scu(env.servers_sources, "*.cpp", "servers"):
    SConscript("arvr/SCsub")
    SConscript("camera/SCsub")
    SConscript("visual/SCsub")
    SConscript("audio/SCsub")

SConscript("physics/SCsub")
SConscript("physics_2d/SCsub")

lib = env.add_library("servers", env.servers_sources)

env.Prepend(LIBS=[lib])
