#pragma clang diagnostic ignored "-Wmissing-braces"

#include "navphysics_error.cpp"
#include "navphysics_loader.cpp"
#include "navphysics_log.cpp"
#include "navphysics_map.cpp"
#include "navphysics_math.cpp"
#include "navphysics_mesh.cpp"
#include "navphysics_plane.cpp"
#include "navphysics_pointf.cpp"
#include "navphysics_pointi.cpp"
#include "navphysics_rect.cpp"
#include "navphysics_region.cpp"
#include "navphysics_sap.cpp"
#include "navphysics_string.cpp"
#include "navphysics_structs.cpp"
#include "navphysics_transform.cpp"
