#!/usr/bin/env python

Import('env')

if env['unity']:
    env.add_source_files(env.scene_sources, "#misc/scu/SCU_scene_gui.cc")
    env.add_source_files(env.scene_sources, "line_edit.cpp")
else:
    env.add_source_files(env.scene_sources, "*.cpp")

