#!/usr/bin/env python

Import("env")

if env["use_scu"]:
    print("SCU building servers physics")
    env.add_source_files(env.servers_sources, "scu/scu_servers_physics.gen.cpp")
else:
    env.add_source_files(env.servers_sources, "*.cpp")
    SConscript("joints/SCsub")
