#!/usr/bin/env python

Import('env')

if env['unity']:
    env.add_source_files(env.servers_sources, "#misc/scu/SCU_servers_physics.cc")
else:
    env.add_source_files(env.servers_sources, "*.cpp")

SConscript("joints/SCsub")
