// Single compilation unit
#include "area_pair_sw.cpp"
#include "area_sw.cpp"
#include "body_pair_sw.cpp"
#include "body_sw.cpp"
#include "broad_phase_basic.cpp"
#include "broad_phase_octree.cpp"
#include "broad_phase_sw.cpp"
#include "collision_object_sw.cpp"
#include "collision_solver_sat.cpp"
#include "collision_solver_sw.cpp"
#include "gjk_epa.cpp"
#include "physics_server_sw.cpp"
#include "shape_sw.cpp"
#include "space_sw.cpp"
#include "step_sw.cpp"
