// Single compilation unit
#include "rasterizer.cpp"
#include "shader_language.cpp"
#include "shader_types.cpp"
#include "visual_server_canvas.cpp"
#include "visual_server_globals.cpp"
#include "visual_server_light_baker.cpp"
#include "visual_server_raster.cpp"
#include "visual_server_scene.cpp"
#include "visual_server_viewport.cpp"
#include "visual_server_wrap_mt.cpp"
