#!/usr/bin/env python

Import("env")
Import("env_modules")

env_bgfx = env_modules.Clone()

print("Compiling BGFX")

# Thirdparty source files
thirdparty_dir = "#thirdparty/bgfx/"

module_obj = []

env_bgfx.add_source_files(module_obj, "*.cpp")
env.modules_sources += module_obj


thirdparty_obj = []

# Godot source files
module_obj = []

env_bgfx.add_source_files(module_obj, "*.cpp")
env.modules_sources += module_obj

# Needed to force rebuilding the module files when the thirdparty library is updated.
env.Depends(module_obj, thirdparty_obj)
env.Append(LIBPATH=["/media/baron/Blue/Home/Pel/Godot/BGFX/bgfx/.build/linux64_gcc/bin"])
env.Prepend(LIBS=["libbgfxDebug.a"])
env.Prepend(LIBS=["libbimgDebug.a"])
env.Prepend(LIBS=["libbxDebug.a"])
